build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Claude Investigator"
  org.opencontainers.image.description: "Automated bug investigation with Claude Code"
  org.opencontainers.image.source: "https://github.com/miquez/claude-investigator-addon"
  org.opencontainers.image.licenses: "MIT"
